---
layout: post
title: "[c#] 클래스의 예외 처리"
description: " "
date: 2023-12-21
tags: [c#]
comments: true
share: true
---

C#에서 예외 처리는 오류 발생 시 프로그램의 안정성을 유지하는 데 중요합니다. 클래스 내에서 예외를 처리하는 방법에 대해 알아보겠습니다.

## 1. 예외 처리 구문

C#에서 클래스 내에서 예외를 처리하려면 `try-catch` 구문을 사용합니다.

```csharp
try
{
    // 예외가 발생할 수 있는 코드
}
catch (Exception ex)
{
    // 예외가 발생했을 때 처리할 코드
}
```

위 코드에서 `try` 블록은 예외가 발생할 수 있는 코드를 포함하고 있습니다. 만약 예외가 발생하면 해당 예외를 잡아내기 위해 `catch` 블록으로 넘어가게 됩니다.

## 2. 예외 처리 방법

### 2.1 특정 예외 처리

특정한 종류의 예외에 대해 처리하고 싶을 경우, 해당 예외 타입을 지정하여 처리할 수 있습니다.

```csharp
try
{
    // 예외가 발생할 수 있는 코드
}
catch (FileNotFoundException ex)
{
    // FileNotFoundException 예외 처리 코드
}
catch (IOException ex)
{
    // IOException 예외 처리 코드
}
```

### 2.2 예외 던지기

예외를 외부로 던져서 상위 호출자에게 예외를 처리하도록 할 수 있습니다.

```csharp
try
{
    if (someCondition)
    {
        throw new CustomException("Something went wrong");
    }
}
catch (CustomException ex)
{
    // CustomException 예외 처리 코드
}
```

## 3. Finally 블록

예외 발생 여부에 상관없이 항상 실행되어야 하는 코드는 `finally` 블록을 사용하여 처리합니다.

```csharp
try
{
    // 예외가 발생할 수 있는 코드
}
catch (Exception ex)
{
    // 예외가 발생했을 때 처리할 코드
}
finally
{
    // 항상 실행되어야 하는 코드
}
```

위의 예제에서 `finally` 블록은 예외 발생 여부와 관계없이 항상 실행됩니다.

예외 처리는 C#에서 안정적인 애플리케이션을 개발하는 데 중요한 요소이며, 적절한 예외 처리를 통해 프로그램의 신뢰성을 높일 수 있습니다.

## 참고 자료
- C# 예외 처리 문서: https://docs.microsoft.com/ko-kr/dotnet/csharp/fundamentals/exceptions/