---
layout: post
title: "[java] RxJava의 에러 복구 전략"
description: " "
date: 2023-11-28
tags: [java]
comments: true
share: true
---

RxJava는 자바에서 사용되는 리액티브 프로그래밍 라이브러리로, 비동기적이고 이벤트 기반의 프로그래밍을 간편하게 구현할 수 있습니다. 그러나 RxJava를 사용할 때 발생하는 에러 처리는 중요한 부분입니다. 이번 블로그 포스트에서는 RxJava에서 에러 복구 전략을 다루어보겠습니다.

## 1. onErrorResumeNext

`onErrorResumeNext` 연산자는 에러가 발생한 경우 다른 Observable로 이어서 작업을 계속할 수 있도록 합니다. 이 연산자를 사용하면 에러가 발생한 Observable을 버리고 대체 Observable을 사용할 수 있습니다. 아래는 `onErrorResumeNext` 연산자의 사용 예제입니다.

```java
Observable.just(1, 2, 3)
    .map(num -> {
        if (num == 2) {
            throw new RuntimeException("Error occurred");
        }
        return num;
    })
    .onErrorResumeNext(Observable.just(4, 5))
    .subscribe(
        System.out::println,
        error -> System.err.println("Error: " + error)
    );
```

위의 코드에서는 `Observable.just(1, 2, 3)`을 생성하고, `map` 연산자에서 값이 2인 경우 에러를 발생시킵니다. 그러면 `onErrorResumeNext` 연산자가 실행되어 대체 Observable인 `Observable.just(4, 5)`로 작업이 이어지게 됩니다.

## 2. onErrorReturn

`onErrorReturn` 연산자는 에러가 발생한 경우 특정 값을 반환하도록 설정할 수 있습니다. 이 연산자를 사용하면 에러가 발생할 때, 에러 대신 설정한 값을 가져올 수 있습니다. 아래는 `onErrorReturn` 연산자의 사용 예제입니다.

```java
Observable.just(1, 2, 3)
    .map(num -> {
        if (num == 2) {
            throw new RuntimeException("Error occurred");
        }
        return num;
    })
    .onErrorReturn(error -> -1)
    .subscribe(
        System.out::println,
        error -> System.err.println("Error: " + error)
    );
```

위의 코드에서도 `Observable.just(1, 2, 3)`을 생성하고, `map` 연산자에서 값이 2인 경우 에러를 발생시킵니다. 그러면 `onErrorReturn` 연산자가 실행되어 -1을 반환하게 됩니다.

## 3. retry

`retry` 연산자는 에러가 발생한 경우 해당 Observable을 다시 실행합니다. 여러 번의 재시도를 통해 에러를 해결할 수 있습니다. 아래는 `retry` 연산자의 사용 예제입니다.

```java
Observable.just(1, 2, 3)
    .map(num -> {
        if (num == 2) {
            throw new RuntimeException("Error occurred");
        }
        return num;
    })
    .retry(2) // 2번의 재시도
    .subscribe(
        System.out::println,
        error -> System.err.println("Error: " + error)
    );
```

위의 코드에서는 값이 2일 때 에러를 발생시키고, `retry` 연산자에 2를 전달하여 2번의 재시도를 수행합니다. 따라서 에러가 발생했더라도 2번의 재시도를 거쳐 최종적으로 성공한 값들을 출력하게 됩니다.

## 결론

RxJava에서 에러 복구 전략을 적절하게 사용하는 것은 안정적인 애플리케이션 개발에 중요합니다. `onErrorResumeNext`, `onErrorReturn`, `retry`와 같은 연산자를 적절하게 활용하여 에러 상황을 대응하는 방법을 익히는 것이 좋습니다. 또한 에러 처리 방법에 대한 자세한 내용은 [RxJava 공식 문서](https://github.com/ReactiveX/RxJava/wiki/Error-Handling-Operators)를 참고하시기 바랍니다.

***References***
- [RxJava 공식 문서 - Error Handling Operators](https://github.com/ReactiveX/RxJava/wiki/Error-Handling-Operators)